name: "Labels: PR"

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'CorvinellaBot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        sync-labels: true
