name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  check_upstream_label:
    name: Check Upstream Label
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.labels.*.name, 'Upstream')
        run: exit 0

  this_aint_right:
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
